server:
  port: 8003

spring:
  application:
    name: data-service
  main:
    banner-mode: console # Disable the Spring logo
    #        web-application-type: none
  #    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  #  datasource:

  #    url: jdbc:mysql://localhost:3306/data?allowpublickeyretrieval=true&usessl=false
  #    username: root
  #    password: A%9jr>NK
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      connection-timeout: 60000
  #      maximum-pool-size: 5
  cache:
    type: redis
    redis:
      time-to-live: 86400000  # 24h
      key-prefix:
        sofa:
      use-key-prefix: true

  spring:
    kafka:
      bootstrap-servers: localhost:9092  # Hoặc cloud Kafka URL
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        group-id: sofa-histories-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: '*'  # Để deserialize custom objects

  data:
    mongodb:
      database: ${MONGODB_DB:football}
      uri: mongodb+srv://${MONGODB_USERNAME:quangnam130520}:${MONGODB_PW:2eixDOgAx1TVcXqp}@${MONGODB_HOST:cluster0.fwoaemp.mongodb.net}/

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  #uri: mongodb+srv://quangnam130520:NLiXVlvZc7Xk6Z4S@cluster0.fwoaemp.mongodb.net/
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8002
          jwk-set-uri: http://localhost:8002/oauth2/jwks
#  jpa:
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: info


api:
  sofa:
    base-url: https://www.sofascore.com/api/v1
    timeout: 5000




#sofascore:
#  api:
#    base-url: https://www.sofascore.com/api/v1